#!/bin/bash

echo "🎨 Render.com Deployment Rehberi - Kurye Backend"
echo "================================================"
echo ""

echo "Railway alternatifi olarak Render.com kullanacağız (100% ücretsiz!)"
echo ""

echo "📋 Adım 1: Render.com'a Kaydolun"
echo "  🔗 https://render.com sitesine gidin"
echo "  🔐 GitHub hesabınızla giriş yapın"
echo ""

echo "📋 Adım 2: Web Service Oluşturun"
echo "  1. Dashboard'da 'New' → 'Web Service'"
echo "  2. GitHub repo'nuzu seçin"
echo "  3. Ayarları yapın:"
echo "     - Name: kurye-backend"
echo "     - Root Directory: backend"
echo "     - Environment: Node"
echo "     - Build Command: npm install"
echo "     - Start Command: npm start"
echo ""

echo "📋 Adım 3: Environment Variables"
echo "  Dashboard'da Environment sekmesinden ekleyin:"
echo ""
echo "  NODE_ENV=production"
echo "  JWT_SECRET=your_secure_jwt_secret_here"
echo "  DATABASE_URL=postgres://username:password@host/database"
echo "  PORT=10000"
echo ""

echo "🗄️  Adım 4: Database Seçenekleri"
echo ""
echo "  A) Render PostgreSQL (Ücretsiz):"
echo "     - Dashboard → 'New' → 'PostgreSQL'"
echo "     - Database URL'ini kopyalayın"
echo ""
echo "  B) Supabase (Ücretsiz):"
echo "     - https://supabase.com hesabı oluşturun"
echo ""
echo "  C) Neon.tech (Ücretsiz):"
echo "     - https://neon.tech hesabı oluşturun"
echo ""

echo "🚀 Adım 5: Deploy"
echo "  - Ayarları kaydedin"
echo "  - Otomatik build başlayacak"
echo "  - URL: https://kurye-backend.onrender.com"
echo ""

echo "🧪 Test Endpoint'leri:"
echo "  - https://your-app.onrender.com/health"
echo "  - https://your-app.onrender.com/api/db-health"
echo ""

echo "✅ JWT Secret oluşturmak için:"
node -e "console.log('JWT_SECRET=' + require('crypto').randomBytes(64).toString('hex'))"
echo ""

echo "🎉 Render.com tamamen ücretsiz ve kredi kartı gerektirmez!"
echo "📚 Detaylı rehber: backend/RENDER_DEPLOYMENT.md" 