import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  listView: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    elevation: 3,
    zIndex: 999,
  },
  scrollViewContent: {
    padding: 20,
    flexGrow: 1,
    height: "140%",
    backgroundColor: "#fff",
  },
  deliveryTimeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  deliveryTimeButton: {
    flex: 1,
    padding: 15,
    marginHorizontal: 5,
    backgroundColor: "#e0e0e0",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
  },
  deliveryTimeButtonSelected: {
    backgroundColor: "#007bff",
    elevation: 5,
  },
  deliveryTimeText: {
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
  },
  timePickerContainer: {
    marginBottom: 20,
  },
  timePickerButton: {
    padding: 15,
    backgroundColor: "#e0e0e0",
    borderRadius: 10,
    alignItems: "center",
    elevation: 3,
  },
  timePickerText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  inputContainer: {
    marginBottom: 20,
    paddingHorizontal: 30,
  },
  inputLabel: {
    fontSize: 16,
    marginBottom: 5,
    color: "#333",
    fontWeight: "500",
  },
  label: {
    fontSize: 16,
    marginBottom: 8,
    color: "#333",
    fontWeight: "500",
  },
  input: {
    height: 50,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    backgroundColor: "#f9f9f9",
    color: "#333",
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 60,
  },
  mapButton: {
    backgroundColor: "#007bff",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    flex: 1,
    marginHorizontal: 5,
    elevation: 3,
  },
  mapButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  mapContainer: {
    height: 300,
    marginTop: 20,
    borderRadius: 10,
    overflow: "hidden",
  },
  map: {
    flex: 1,
  },
  footer: {
    backgroundColor: "#fff",
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    position: "absolute",
    left: 0,
    bottom: 80,
    right: 0,
    elevation: 10,
  },
  saveButton: {
    backgroundColor: "#28a745",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    elevation: 5,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
});